# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see <https://docs.haskellstack.org/en/stable/travis_ci/>.

# Use new container infrastructure to enable caching
sudo: false

# Enable Nix
language: nix

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export "PATH=$HOME/.local/bin:$PATH"
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-nix -j2 --no-terminal --install-ghc test --only-dependencies

script:
  # Build the package, its tests, and its docs, and run the tests
  - stack --no-nix -j2 --no-terminal test --haddock --no-haddock-deps --coverage

after_script:
  # Collect and submit coverage information
  # - stack --no-nix install stack-hpc-coveralls
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
  - ./shc wavetoy1 wavetoy1-test-suite
