# This YAML file describes your package. Stack will automatically
# generate a Cabal file when you run `stack build`. See the hpack
# website for help with this file: <https://github.com/sol/hpack>.
benchmarks:
  wavetoy1-benchmarks:
    dependencies:
    - base
    - criterion
    - wavetoy1
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: wavetoy1 is a Haskell WaveToy implementation
executables:
  wavetoy1:
    dependencies:
    - base
    - monad-loops
    - wavetoy1
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.rst
- LICENSE.rst
- package.yaml
- README.rst
- stack.yaml
ghc-options: -Wall
github: eschnett/wavetoy1
library:
  dependencies:
  - base
  - vector
  source-dirs: library
license: MIT
maintainer: Erik Schnetter
name: wavetoy1
synopsis: wavetoy1 is a Haskell WaveToy implementation
tests:
  wavetoy1-test-suite:
    dependencies:
    - base
    - ieee754
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
    - vector
    - wavetoy1
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
