dependencies:
  cache_directories:
    - "~/.stack"
  pre:
    # Download and unpack the stack executable
    - mkdir -p "$HOME/.local/bin"
    - export "PATH=$HOME/.local/bin:$PATH"
    - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64.tar.gz | tar zx -C "$HOME/.local/bin" '*/stack'
    - curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar xj -C "$HOME/.local/bin"
  override:
    # Build dependencies
    - stack -j2 --no-terminal --install-ghc test --only-dependencies

test:
  override:
    # Build the package, its tests, and its docs, and run the tests
    - stack -j2 --no-terminal test --haddock --no-haddock-deps --coverage
  post:
    # Collect and submit coverage information
    - shc wavetoy1 wavetoy1-test-suite
