version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Download and unpack the stack executable
          command: |
            apt-get install libgmp-dev
            mkdir -p "$HOME/.local/bin"
            export "PATH=$HOME/.local/bin:$PATH"
            curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
            curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar xj -C "$HOME/.local/bin"
      - run:
          name: Build dependencies
          command: |
            export "PATH=$HOME/.local/bin:$PATH"
            stack -j2 --no-nix --no-terminal --install-ghc test --only-dependencies
      - run:
          name: Build the package, its tests, and its docs, and run the tests
          command: |
            export "PATH=$HOME/.local/bin:$PATH"
            stack -j2 --no-nix --no-terminal test --haddock --no-haddock-deps --coverage
      - run:
          name: Collect and submit coverage information
          command: |
            export "PATH=$HOME/.local/bin:$PATH"
            shc wavetoy1 wavetoy1-test-suite
    
#   cache_directories:
#     - "~/.stack"
